// AUTO-GENERATED by tools/mkpcm_blob.mjs — do not edit.
// Time Pilot IIvera 6.5kHz PCM table resident in VRAM Bank 0 ($2000..$0FFFF).
#pragma once
#include <stdint.h>
typedef struct { uint16_t start; uint16_t length; uint8_t loops; } TpAudioData;
#define NUM_AUDIO_SOURCES 20
#define VERA_PCM_RATE 17  // ~6485 Hz (25MHz/512 * 17/128)
#define VRAM_AUDIO_BASE 0x2000
#define PCM_START_BLOCK 200
#define PCM_TOTAL_BYTES 52830
#define PCM_NUM_BLOCKS  104

static const TpAudioData audioData[NUM_AUDIO_SOURCES] = {
    { 0x2000, 0x0A22, 0 }, // AUDIO_COINDROP
    { 0x2A22, 0x1444, 0 }, // AUDIO_GAME_START
    { 0x3E66, 0x0000, 0 }, // AUDIO_HIGHSCORE
    { 0x3E66, 0x1444, 0 }, // AUDIO_NEXT_LEVEL
    { 0x52AA, 0x0332, 0 }, // AUDIO_PLAYER_SHOOT
    { 0x55DC, 0x07B0, 1 }, // AUDIO_ROCKET_FLY
    { 0x5D8C, 0x04B9, 1 }, // AUDIO_BOSSL0
    { 0x6245, 0x0D16, 1 }, // AUDIO_BOSSL1
    { 0x6F5B, 0x040F, 1 }, // AUDIO_BOSSL2
    { 0x736A, 0x04E7, 1 }, // AUDIO_BOSSL3
    { 0x7851, 0x0DFB, 0 }, // AUDIO_WAPON_EXPLODE
    { 0x864C, 0x0CC1, 0 }, // AUDIO_ENEMY_EXPLODE
    { 0x930D, 0x04F8, 0 }, // AUDIO_ENEMY_SHOOT
    { 0x9805, 0x0F17, 0 }, // AUDIO_BOMB
    { 0xA71C, 0x08AF, 0 }, // AUDIO_ROCKET_LAUNCH
    { 0xAFCB, 0x1223, 0 }, // AUDIO_PICKUP
    { 0xC1EE, 0x0F83, 0 }, // AUDIO_EXTRA_LIFE
    { 0xD171, 0x08A9, 0 }, // AUDIO_WAVE_START
    { 0xDA1A, 0x1444, 0 }, // AUDIO_BIG_EXPLOSION
    { 0xEE5E, 0x0000, 0 }, // AUDIO_TIMEWARP
};
