import fs from 'fs';
import path from 'path';
import zlib from 'zlib';

async function getVgm() {
  const vgmPath = 'build/game_start.vgm';
  if (fs.existsSync(vgmPath)) {
    return fs.readFileSync(vgmPath);
  }
  fs.mkdirSync('build', { recursive: true });
  console.log('Downloading Arcade Game Start VGM from VGMRips...');
  const url = 'https://vgmrips.net/packs/vgm/Arcade/Time_Pilot_%28Arcade%29/01%20Game%20Start.vgz';
  const res = await fetch(url);
  const vgzBuf = Buffer.from(await res.arrayBuffer());
  const vgm = zlib.gunzipSync(vgzBuf);
  fs.writeFileSync(vgmPath, vgm);
  return vgm;
}

async function run() {
const vgm = await getVgm();
let p = 128;
let sampleTime = 0;
const frameEvents = new Map();

while (p < vgm.length) {
  const cmd = vgm[p++];
  if (cmd === 0x66) break;
  else if (cmd === 0x61) { sampleTime += vgm.readUInt16LE(p); p += 2; }
  else if (cmd === 0x62) sampleTime += 735;
  else if (cmd === 0x63) sampleTime += 882;
  else if ((cmd & 0xF0) === 0x70) sampleTime += (cmd & 0x0F) + 1;
  else if (cmd === 0xA0) {
    const r = vgm[p++];
    const v = vgm[p++];
    const frame = Math.round(sampleTime * 60 / 44100);
    if (!frameEvents.has(frame)) frameEvents.set(frame, []);
    frameEvents.get(frame).push({ r, v });
  }
}

const maxFrame = Math.max(...frameEvents.keys());

// AY 0..15 volume to VERA PSG 0..63 volume
// In arcade Time Pilot, the game start theme uses volume 0..8 as the dynamic range,
// where 8 is the peak note volume and decays down to 1.
// We map 8 -> 63 (0x3F, full VERA volume) for loud, clear arcade playback.
const AY_TO_VERA_VOL = [
   0,  8, 16, 24, 32, 40, 48, 56, 63,
  63, 63, 63, 63, 63, 63, 63
];

const regs = new Uint8Array(256);
const chState = [ {freq:0, vol:0}, {freq:0, vol:0}, {freq:0, vol:0}, {freq:0, vol:0} ];
const events = [];

let lastFrame = 0;

for (let f = 0; f <= maxFrame + 5; f++) {
  if (frameEvents.has(f)) {
    for (const { r, v } of frameEvents.get(f)) {
      regs[r] = v;
    }
  }

  const newPeriods = [
    regs[0] | ((regs[1] & 0x0F) << 8),
    regs[2] | ((regs[3] & 0x0F) << 8),
    regs[4] | ((regs[5] & 0x0F) << 8),
    regs[128] | ((regs[129] & 0x0F) << 8),
  ];
  const newVols = [
    (regs[7] & 1) === 0 ? (regs[8] & 0x0F) : 0,
    (regs[7] & 2) === 0 ? (regs[9] & 0x0F) : 0,
    (regs[7] & 4) === 0 ? (regs[10] & 0x0F) : 0,
    (regs[135] & 1) === 0 ? (regs[136] & 0x0F) : 0,
  ];

  let frameChanged = false;
  const changesInFrame = [];

  for (let ch = 0; ch < 4; ch++) {
    const period = newPeriods[ch];
    const ayVol = newVols[ch];
    const veraVol = AY_TO_VERA_VOL[ayVol];
    const veraFreq = (period > 0 && veraVol > 0) ? Math.round(150137 / period) : 0;

    if (chState[ch].freq !== veraFreq || chState[ch].vol !== veraVol) {
      changesInFrame.push({ ch, freq: veraFreq, vol: veraVol });
      chState[ch].freq = veraFreq;
      chState[ch].vol = veraVol;
    }
  }

  if (changesInFrame.length > 0) {
    let delta = f - lastFrame;
    lastFrame = f;

    // If delta > 254, emit dummy wait events
    while (delta > 254) {
      events.push({ delta: 254, ch: 0, vol: chState[0].vol, freq: chState[0].freq, dummy: true });
      delta -= 254;
    }

    for (let i = 0; i < changesInFrame.length; i++) {
      const c = changesInFrame[i];
      events.push({
        delta: (i === 0) ? delta : 0,
        ch: c.ch,
        vol: c.vol,
        freq: c.freq
      });
    }
  }
}

// End marker
events.push({ delta: 255, ch: 0, vol: 0, freq: 0 });

console.log(`Generated ${events.length} PSG theme events.`);

// Format C header
let cCode = `// AUTO-GENERATED by tools/gen_psg_theme.mjs — do not edit.
// Time Pilot Arcade opening theme converted to 4-voice VERA PSG events (Channels 6..9).
#pragma once
#include <stdint.h>

typedef struct {
    uint8_t delta;  /* 60Hz frames to wait before this event (0 = simultaneous, 255 = end of song) */
    uint8_t ch_vol; /* (channel 0..3 << 6) | (VERA vol 0..63) */
    uint16_t freq;  /* VERA 14-bit frequency word */
} PsgThemeEvent;

#define PSG_THEME_EVENTS_COUNT ${events.length}
#define CH_THEME_BASE 0  /* Channels 0, 1, 2, 3 (primary PSG channels) */

static const PsgThemeEvent themePsgEvents[${events.length}] = {
`;

for (let i = 0; i < events.length; i++) {
  const e = events[i];
  const chVol = ((e.ch & 3) << 6) | (e.vol & 0x3F);
  cCode += `    { ${e.delta}, 0x${chVol.toString(16).toUpperCase().padStart(2, '0')}, ${e.freq} },\n`;
}

cCode += `};
`;

fs.writeFileSync('src/theme_psg.h', cCode);
console.log('Written src/theme_psg.h successfully! Total bytes: ~' + (events.length * 4) + ' bytes in binary.');
}

run();
