// mkart.mjs — Extract all sprite art from src/art.h into build/art.blob and
// emit src/art_table.h with byte offsets. This removes the ~17KB of art from
// the binary (which was causing "NO BUFFERS AVAILABLE" on BRUN) and puts it on
// the HDV for MLI streaming into VERA pattern RAM at boot (the CX16 .vrm model).
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const projectRoot = path.resolve(__dirname, "..")
const buildDir = path.join(projectRoot, "build")
fs.mkdirSync(buildDir, { recursive: true })

// HDV block where art.blob begins. KEEP IN SYNC with build_hdv.mjs.
const ART_START_BLOCK = 900
const BLOCK = 512

const text = fs.readFileSync(path.join(projectRoot, "src", "art.h"), "utf8")

// Parse each `static const uint8_t NAME[A][B] = { ... };` by brace-matching.
const arrays = []
const declRe = /static const uint8_t (\w+)\[(\d+)\]\[(\d+)\]\s*=\s*\{/g
let m
while ((m = declRe.exec(text))) {
  const name = m[1]
  const dims = [Number(m[2]), Number(m[3])]
  const expected = dims[0] * dims[1]
  // Brace-match from the first '{' (declRe already consumed it; m.index + m[0].length is right after '{').
  let i = m.index + m[0].length - 1  // position of the '{'
  let depth = 0, start = -1
  while (i < text.length) {
    const ch = text[i]
    if (ch === "{") { depth++; if (depth === 1) start = i + 1 }
    else if (ch === "}") { depth--; if (depth === 0) break }
    i++
  }
  const body = text.slice(start, i)
  const cleanBody = body.replace(/\/\*[\s\S]*?\*\//g, "").replace(/\/\/.*/g, "")
  const bytes = (cleanBody.match(/(?:0x[0-9a-fA-F]+|\b\d+\b)/g) || []).map(Number)
  if (bytes.length !== expected) {
    throw new Error(`${name}: parsed ${bytes.length} bytes, expected ${expected}`)
  }
  for (const b of bytes) if (b < 0 || b > 255) throw new Error(`${name}: byte ${b} out of range`)
  arrays.push({ name, dims, bytes, size: bytes.length })
}

// Concatenate into the blob (declaration order).
const blobParts = []
let off = 0
const entries = arrays.map((a) => {
  const e = { name: a.name, off, len: a.size }
  blobParts.push(new Uint8Array(a.bytes))
  off += a.size
  return e
})
const total = off
fs.writeFileSync(path.join(buildDir, "art.blob"), Buffer.concat(blobParts))
const numBlocks = Math.ceil(total / BLOCK)

// Emit art_table.h.
const hex32 = (n) => "0x" + n.toString(16).toUpperCase().padStart(8, "0") + "UL"
let header = [
  "// AUTO-GENERATED by tools/mkart.mjs — do not edit.",
  "// Time Pilot IIvera sprite-art blob offsets (palette-index bitmaps).",
  "#pragma once",
  "#include <stdint.h>",
  `#define ART_START_BLOCK ${ART_START_BLOCK}`,
  `#define ART_TOTAL_BYTES ${total}`,
  `#define ART_NUM_BLOCKS  ${numBlocks}`,
  "",
]
for (const e of entries) {
  const c = e.name.toUpperCase()
  header.push(`#define ART_${c}_OFF ${hex32(e.off)}`)
  header.push(`#define ART_${c}_LEN ${hex32(e.len)}`)
}
header.push("")
fs.writeFileSync(path.join(projectRoot, "src", "art_table.h"), header.join("\n"))

console.log(`art.blob: ${total} bytes (${numBlocks} blocks) -> build/art.blob`)
console.log(`  ${entries.length} arrays:`, entries.map((e) => e.name).join(", "))
console.log(`  ART_START_BLOCK = ${ART_START_BLOCK} (blocks ${ART_START_BLOCK}..${ART_START_BLOCK + numBlocks - 1})`)
