#!/usr/bin/env python3
"""mkart.py - Extract all sprite art from src/art.h into art.blob and emit
src/art_table.h with byte offsets.

This keeps the ~17KB of art out of the load image and puts it on the disk
image for MLI streaming into VERA pattern RAM at boot (the CX16 .vrm model).

Ported from the original mkart.mjs.
"""

import argparse
import os
import re
import sys

# Disk block where art.blob begins. KEEP IN SYNC with build_hdv.py.
ART_START_BLOCK = 900
BLOCK = 512

DECL_RE = re.compile(r"static const uint8_t (\w+)\[(\d+)\]\[(\d+)\]\s*=\s*\{")
COMMENT_BLOCK_RE = re.compile(r"/\*.*?\*/", re.S)
COMMENT_LINE_RE = re.compile(r"//.*")
NUMBER_RE = re.compile(r"0x[0-9a-fA-F]+|\b\d+\b")


def parse_arrays(text):
    """Parse each `static const uint8_t NAME[A][B] = { ... };` by brace-matching."""
    arrays = []
    for m in DECL_RE.finditer(text):
        name = m.group(1)
        dims = (int(m.group(2)), int(m.group(3)))
        expected = dims[0] * dims[1]

        # Brace-match from the '{' the declaration regex just consumed.
        i = m.end() - 1
        depth = 0
        start = -1
        while i < len(text):
            ch = text[i]
            if ch == "{":
                depth += 1
                if depth == 1:
                    start = i + 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    break
            i += 1

        body = text[start:i]
        body = COMMENT_BLOCK_RE.sub("", body)
        body = COMMENT_LINE_RE.sub("", body)
        values = [int(v, 0) for v in NUMBER_RE.findall(body)]

        if len(values) != expected:
            raise SystemExit(
                f"{name}: parsed {len(values)} bytes, expected {expected}")
        for b in values:
            if b < 0 or b > 255:
                raise SystemExit(f"{name}: byte {b} out of range")

        arrays.append((name, bytes(values)))
    return arrays


def hex32(n):
    return "0x%08XUL" % n


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(here)

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--src-dir", default=os.path.join(project_root, "src"),
                    help="directory holding art.h (default: <project>/src)")
    ap.add_argument("--build-dir", default=os.path.join(project_root, "build"),
                    help="directory to write art.blob into (default: <project>/build)")
    args = ap.parse_args()

    os.makedirs(args.build_dir, exist_ok=True)

    art_h = os.path.join(args.src_dir, "art.h")
    with open(art_h, "r", encoding="utf-8") as f:
        text = f.read()

    arrays = parse_arrays(text)
    if not arrays:
        raise SystemExit(f"no sprite arrays found in {art_h}")

    # Concatenate into the blob, in declaration order.
    entries = []
    parts = []
    off = 0
    for name, data in arrays:
        entries.append((name, off, len(data)))
        parts.append(data)
        off += len(data)
    total = off
    blob = b"".join(parts)

    blob_path = os.path.join(args.build_dir, "art.blob")
    with open(blob_path, "wb") as f:
        f.write(blob)

    num_blocks = (total + BLOCK - 1) // BLOCK

    header = [
        "// AUTO-GENERATED by tools/mkart.py - do not edit.",
        "// Time Pilot IIvera sprite-art blob offsets (palette-index bitmaps).",
        "#pragma once",
        "#include <stdint.h>",
        f"#define ART_START_BLOCK {ART_START_BLOCK}",
        f"#define ART_TOTAL_BYTES {total}",
        f"#define ART_NUM_BLOCKS  {num_blocks}",
        "",
    ]
    for name, off, length in entries:
        c = name.upper()
        header.append(f"#define ART_{c}_OFF {hex32(off)}")
        header.append(f"#define ART_{c}_LEN {hex32(length)}")
    header.append("")

    with open(os.path.join(args.src_dir, "art_table.h"), "w",
              encoding="utf-8") as f:
        f.write("\n".join(header))

    print(f"art.blob: {total} bytes ({num_blocks} blocks) -> {blob_path}")
    print(f"  {len(entries)} arrays: " + ", ".join(e[0] for e in entries))
    print(f"  ART_START_BLOCK = {ART_START_BLOCK} "
          f"(blocks {ART_START_BLOCK}..{ART_START_BLOCK + num_blocks - 1})")


if __name__ == "__main__":
    sys.exit(main())
